export {default as About} from './about/about'
export {default as Brand} from './brand/brand'
export {default as Head} from './head/head'
export {default as Find} from './find/find'
export {default as Team} from './team/team'
export {default as List} from './listing/list'