export const homes = [
  {
    id: "1",
    def: "asset/d14.jfif",
    des: "One of a kind house in the beautiful location of Los Angeles. Designed by Lucy De Vito and built in the 2020 to a very high standard, this spectacular residence has been thoughtfully designed for family living in an uncluttered and special space.",
    imgs: [
      "asset/d2.jfif",
      "asset/d3.jfif",
      "asset/d1.jfif",
      "asset/d4.jfif",
      "asset/d5.jfif",
      "asset/d5.jfif",
    ],
    bed: "/asset/bed.png",
    car: "asset/car.png",
    shawa: "asset/sho.png",
    sq: "asset/ruler.png",
    size: "1200 sq ft",
    amt: "$11,000/mo",
    typ: "APARTMENT",
    tit: "Modern Apartment",
    status: " FOR RENT",
    val: "4",
    carn: "1",
    shawn: "2",
    left: "<",
    right: ">",
  },
  {
    id: "2",
    def: "asset/d12.jfif",
    des: "One of a kind house in the beautiful location of Los Angeles. Designed by Lucy De Vito and built in the 2020 to a very high standard, this spectacular residence has been thoughtfully designed for family living in an uncluttered and special space.",
    imgs: [
      "asset/d5.jfif",
      "asset/d10.jfif",
      "asset/d2.jfif",
      "asset/d3.jfif",
      "asset/d4.jfif",
      "asset/d5.jfif",
    ],
    bed: "/asset/bed.png",
    car: "asset/car.png",
    shawa: "asset/sho.png",
    sq: "asset/ruler.png",
    size: "1200 sq ft",
    amt: "$18,500/mo",
    typ: "APARTMENT",
    tit: "Modern Apartment",
    status: " FOR RENT",
    val: "3",
    carn: "1",
    shawn: "2",
    left: "<",
    right: ">",
  },
  {
    id: "3",
    def: "asset/d1.jfif",
    des: "One of a kind house in the beautiful location of New York. Designed by Lucy De Vito and built in the 2020 to a very high standard, this spectacular residence has been thoughtfully designed for family living in an uncluttered and special space.",
    imgs: [
      "asset/d1.jfif",
      "asset/d4.jfif",
      "asset/d2.jfif",
      "asset/d3.jfif",
      "asset/d5.jfif",
      "asset/d5.jfif",
    ],
    bed: "/asset/bed.png",
    car: "asset/car.png",
    shawa: "asset/sho.png",
    sq: "asset/ruler.png",
    size: "1200 sq ft",
    amt: "$13,900/mo",
    typ: "APARTMENT",
    tit: "Modern Apartment",
    status: " FOR RENT",
    val: "4",
    carn: "1",
    shawn: "2",
    left: "<",
    right: ">",
  },
  {
    id: "4",
    def: "asset/d4.jfif",
    imgs: [
      "asset/d222.jpg",
      "asset/d1.jfif",
      "asset/d3.jfif",
      "asset/d2.jfif",
      "asset/d4.jfif",
      "asset/d5.jfif",
      "asset/d5.jfif",
    ],
    bed: "/asset/bed.png",
    car: "asset/car.png",
    shawa: "asset/sho.png",
    sq: "asset/ruler.png",
    size: "1200 sq ft",
    amt: "$17,000/mo",
    typ: "APARTMENT",
    tit: "Modern Apartment",
    status: " FOR RENT",
    val: "4",
    carn: "1",
    shawn: "2",
    left: "<",
    right: ">",
  },
  {
    id: "5",
    des: "One of a kind house in the beautiful location of Michigan. Designed by Lucy De Vito and built in the 2020 to a very high standard, this spectacular residence has been thoughtfully designed for family living in an uncluttered and special space.",
    def: "asset/d11.jfif",
    imgs: [
      "asset/d4.jfif",
      "asset/d1.jfif",
      "asset/d2.jfif",
      "asset/d3.jfif",
      "asset/d5.jfif",
      "asset/d5.jfif",
    ],
    bed: "/asset/bed.png",
    car: "asset/car.png",
    shawa: "asset/sho.png",
    sq: "asset/ruler.png",
    size: "1200 sq ft",
    amt: "$15,000/mo",
    typ: "APARTMENT",
    tit: "Modern Apartment",
    status: " FOR RENT",
    val: "5",
    carn: "1",
    shawn: "2",
    left: "<",
    right: ">",
  },
  {
    id: "6",
    des: "One of a kind house in the beautiful location of California. Designed by Lucy De Vito and built in the 2020 to a very high standard, this spectacular residence has been thoughtfully designed for family living in an uncluttered and special space.",
    def: "asset/d19.jfif",
    imgs: [
      "asset/int5a.jpg",
      "asset/d5.jfif",
      "asset/d1.jfif",
      "asset/d2.jfif",
      "asset/d3.jfif",
      "asset/d4.jfif",
      "asset/d5.jfif",
    ],
    bed: "/asset/bed.png",
    car: "asset/car.png",
    shawa: "asset/sho.png",
    sq: "asset/ruler.png",
    size: "1200 sq ft",
    amt: "$13,600/mo",
    typ: "APARTMENT",
    tit: "Modern Apartment",
    status: " FOR RENT",
    val: "3",
    carn: "1",
    shawn: "2",
    left: "<",
    right: ">",
  },
];

export const classic = [
  {
    name: "bello",
    id: "1",
    team: ["asset/d5.jfif", "asset/d3.jfif", "asset/d4.jfif"],
    left: "<",
    right: ">",
  },
  {
    name: "isa",
    id: "2",
    team: ["asset/d2.jfif", "asset/d4.jfif", "asset/d5.jfif"],
    left: "<",
    right: ">",
  },
  {
    name: "mike",
    id: "3",
    team: ["asset/d3.jfif", "asset/d2.jfif", "asset/d40.jfif"],
    left: "<",
    right: ">",
  },
];
